
#define NK_IMPLEMENTATION
#define NK_SDL_GL3_IMPLEMENTATION
#define DEBUG_DRAW_IMPLEMENTATION
#define TINYFILES_IMPL
#define NOC_FILE_DIALOG_IMPLEMENTATION
#define NOC_FILE_DIALOG_WIN32
#define INI_IMPLEMENTATION

#include "Implementation.h"
